// ─────────────────────────────────────────────
// File: scripts/seed-word-catalog.ts
// Purpose: Generates SQL INSERT statements for the
//          leaderboard_word_catalog table from the word bank
//          and kana character data. Uses the same romaji
//          normalization as runtime (sokuon, longvowel).
//          Run: npx tsx scripts/seed-word-catalog.ts > supabase/migrations/[ts]_seed_word_catalog.sql
// Depends on: data/words/n5..n1, data/kana/characters.ts
// ─────────────────────────────────────────────

import { N5_WORDS } from '../data/words/n5'
import { N4_WORDS } from '../data/words/n4'
import { N3_WORDS } from '../data/words/n3'
import { N2_WORDS } from '../data/words/n2'
import { N1_WORDS } from '../data/words/n1'
import { KANA_CHARACTERS } from '../data/kana/characters'

// ── Character lookup ────────────────────────

const charMap = new Map(KANA_CHARACTERS.map((c) => [c.id, { kana: c.kana, romaji: c.romaji }]))

// ── Romaji normalization (matches runtime) ──

const SOKUON_IDS = new Set(['h-sokuon', 'k-sokuon'])
const LONGVOWEL_ID = 'k-longvowel'

function getFirstConsonant(romaji: string): string {
  const vowels = 'aiueo'
  if (romaji.length > 0 && !vowels.includes(romaji[0])) return romaji[0]
  return 't'
}

function getLastVowel(romaji: string): string {
  const vowels = 'aiueo'
  for (let i = romaji.length - 1; i >= 0; i--) {
    if (vowels.includes(romaji[i])) return romaji[i]
  }
  return 'u'
}

function normalizeRomaji(
  charIds: string[],
  rawChars: Array<{ kana: string; romaji: string }>,
): { romaji: string[]; kana: string[] } {
  const romaji: string[] = []
  const kana: string[] = []

  for (let i = 0; i < charIds.length; i++) {
    const ch = rawChars[i]
    const id = charIds[i]

    if (SOKUON_IDS.has(id)) {
      const next = rawChars[i + 1]
      romaji.push(next ? getFirstConsonant(next.romaji) : 't')
    } else if (id === LONGVOWEL_ID) {
      const prev = rawChars[i - 1]
      romaji.push(prev ? getLastVowel(prev.romaji) : 'u')
    } else {
      romaji.push(ch.romaji)
    }

    kana.push(ch.kana)
  }

  return { romaji, kana }
}

// ── Collect words ───────────────────────────

const allWords = [...N5_WORDS, ...N4_WORDS, ...N3_WORDS, ...N2_WORDS, ...N1_WORDS]

// ── Build rows ──────────────────────────────

function escapeSql(s: string): string {
  return s.replace(/'/g, "''")
}

const rows: string[] = []
let skipped = 0

for (const word of allWords) {
  if (word.id.length === 0) {
    skipped++
    continue
  }

  const rawChars: Array<{ kana: string; romaji: string }> = []
  let valid = true

  for (const charId of word.characterIds) {
    const ch = charMap.get(charId)
    if (!ch) {
      valid = false
      break
    }
    rawChars.push(ch)
  }

  if (!valid || rawChars.length === 0) {
    skipped++
    continue
  }

  const { romaji, kana } = normalizeRomaji(word.characterIds, rawChars)

  const wordId = escapeSql(word.id)
  const charCount = romaji.length
  const hasKanji = word.kanji !== null
  const romajiJson = JSON.stringify(romaji)
  const kanaJson = JSON.stringify(kana)
  const kanjiVal = word.kanji ? `'${escapeSql(word.kanji)}'` : 'null'

  rows.push(
    `  ('${wordId}', ${charCount}, ${hasKanji}, '${escapeSql(romajiJson)}'::jsonb, '${escapeSql(kanaJson)}'::jsonb, ${kanjiVal})`,
  )
}

// ── Output SQL ──────────────────────────────

console.log('-- Generated by scripts/seed-word-catalog.ts')
console.log(`-- ${rows.length} words, ${skipped} skipped`)
console.log('')
console.log(
  'insert into public.leaderboard_word_catalog (word_id, char_count, has_kanji, expected_romaji, expected_kana, kanji) values',
)
console.log(rows.join(',\n'))
console.log('on conflict (word_id) do update set')
console.log('  char_count = excluded.char_count,')
console.log('  has_kanji = excluded.has_kanji,')
console.log('  expected_romaji = excluded.expected_romaji,')
console.log('  expected_kana = excluded.expected_kana,')
console.log('  kanji = excluded.kanji;')

process.stderr.write(`Wrote ${rows.length} rows, skipped ${skipped}\n`)
