// ─────────────────────────────────────────────
// File: scripts/seed-kana-catalog.ts
// Purpose: Generates SQL INSERT statements for the
//          kana_character_catalog table from the kana
//          character data. Used for server-side ID validation
//          in checkpoint and import RPCs.
//          Run: npx tsx scripts/seed-kana-catalog.ts
// Depends on: data/kana/characters.ts
// ─────────────────────────────────────────────

import { KANA_CHARACTERS } from '../data/kana/characters'

function escapeSql(s: string): string {
  return s.replace(/'/g, "''")
}

const rows = KANA_CHARACTERS.map((c) => {
  const id = escapeSql(c.id)
  const kana = escapeSql(c.kana)
  const romaji = escapeSql(c.romaji)
  const type = c.script === 'hiragana' ? 'hiragana' : 'katakana'
  return `  ('${id}', '${kana}', '${romaji}', '${type}')`
})

const sql = [
  '-- Generated by scripts/seed-kana-catalog.ts',
  `-- ${rows.length} characters`,
  '',
  'insert into public.kana_character_catalog (character_id, kana, romaji, type) values',
  rows.join(',\n'),
  'on conflict (character_id) do update set',
  '  kana = excluded.kana,',
  '  romaji = excluded.romaji,',
  '  type = excluded.type;',
].join('\n')

process.stdout.write(sql + '\n')
process.stderr.write(`Wrote ${rows.length} characters\n`)
